config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    root                            to: 'home#index'
    get 'index',                    to: 'home#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'

    resources :products,            only: [:show, :index]
    resources :categories,          only: [:show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  scope :includes_price_and_images,           -> { includes(master: [:default_price, :images]) }
  scope :same_taxons_product,                 -> (product) {
                                                joins(:taxons).
                                                  where(spree_taxons: { id: product.taxons.ids }).
                                                  distinct
                                              }
  scope :exclude_product,                     -> (product) { where.not(id: product.id) }
  scope :filter_by_option,                    -> (option) {
    if option[:option_value].present?
      joins(variants: :option_values).
        where(spree_option_values: { name: option[:option_value] })
    end
  }
  scope :sort_descend_by_price,               -> { order("spree_prices.amount DESC") }
  scope :sort_ascend_by_price,                -> { order("spree_prices.amount ASC") }
  scope :sort_newest_by_product_available_on, -> { order("spree_products.available_on DESC") }
  scope :sort_oldest_by_product_available_on, -> { order("spree_products.available_on ASC") }
  scope :order_by,                            ->(order) {
                                                case order
                                                when 'price-dsc' then sort_descend_by_price
                                                when 'price-asc' then sort_ascend_by_price
                                                when 'oldest'
                                                   then sort_oldest_by_product_available_on
                                                else sort_newest_by_product_available_on
                                                end
                                              }
end

app/models/spree/variant_decorator.rb
Spree::Variant.class_eval do
  scope :includes_price, -> { includes(:product, :default_price) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  def show
    @taxon = Spree::Taxon.find(params[:id])
    @taxonomies = Spree::Taxonomy.all.includes(root: :children)
    @products = if params[:order]
                  Spree::Product.in_taxon(@taxon).
                    includes_price_and_images.
                    filter_by_option(option_value: params[:option_value]).
                    reorder(nil).
                    order_by(params[:order])
                else
                  Spree::Product.in_taxon(@taxon).
                    includes_price_and_images.
                    filter_by_option(option_value: params[:option_value])
                end
    @list_of_colors = Spree::OptionType.find_by(name: 'tshirt-color').option_values
    @list_of_sizes = Spree::OptionType.find_by(name: 'tshirt-size').option_values
  end
end

app/controllers/potepan/home_controller.rb
class Potepan::HomeController < ApplicationController
  THE_NUMBER_OF_NEW_PRODUCTS = 10

  def index
    @new_products = Spree::Product.
      includes_price_and_images.
      order(available_on: :desc).
      limit(THE_NUMBER_OF_NEW_PRODUCTS)

    @clothing = Spree::Taxon.where(name: "Clothing")
    @bags = Spree::Taxon.where(name: "Bags")
    @mugs = Spree::Taxon.where(name: "Mugs")
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  THE_NUMBER_OF_RELATED_PRODUCTS = 4

  def show
    if Spree::Product.where(id: params[:id]).present?
      @product = Spree::Product.find(params[:id])
      @related_products = Spree::Product.includes_price_and_images.
        same_taxons_product(@product).
        exclude_product(@product).
        limit(THE_NUMBER_OF_RELATED_PRODUCTS)
    else
      @product = Spree::Variant.find(params[:id])
      @related_products = Spree::Product.includes_price_and_images.
        same_taxons_product(@product.product).
        exclude_product(@product).
        limit(THE_NUMBER_OF_RELATED_PRODUCTS)
    end
  end

  def index
    @option_value = Spree::OptionValue.find_by(name: params[:option])
    @products = @option_value.variants.includes_price
    @taxon = Spree::Taxon.first
    @taxonomies = Spree::Taxonomy.all.includes(root: :children)
    @list_of_colors = Spree::OptionType.find_by(name: 'tshirt-color').option_values
    @list_of_sizes = Spree::OptionType.find_by(name: 'tshirt-size').option_values
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  layout 'sample'

  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "BIGBAG Store"
    if page_title.empty?
      base_title
    else
      page_title + " - " + base_title
    end
  end
end

app/views/layouts/_copyright.html.erb
<!-- COPY RIGHT -->
<div class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2018 Copyright Potepan Store .</p>
      </div>
      <div class="col-sm-5 col-xs-12">
        <ul class="list-inline">
          <li>
            <a href="#">
              <i class="fa fa-twitter"></i>
            </a>
          </li>
          <li>
            <a href="#">
              <i class="fa fa-facebook"></i>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<!-- FOOTER -->
<div class="footer clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-2 col-xs-12">
        <div class="footerLink">
          <h5>商品をお探しなら</h5>
          <ul class="list-unstyled">
            <li>
              <a href="product-grid-left-sidebar.html">SHOES</a>
            </li>
            <li>
              <a href="product-grid-left-sidebar.html">BAGS
              </a>
            </li>
            <li>
              <a href="product-grid-left-sidebar.html">GLASSES
              </a>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-sm-2 col-xs-12">
        <div class="footerLink">
          <h5>BIGBAGについて</h5>
          <ul class="list-unstyled">
            <li>
              <%= link_to 'ABOUT US', potepan_about_us_path %>
            </li>
            <li>
              <%= link_to 'プライバシーポリシー', potepan_privacy_policy_path %>
            </li>
            <li>
              <%= link_to '特定商取引法についての表記', potepan_tokushoho_path %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<!-- HEADER -->
<div class="header clearfix">

  <!-- TOPBAR -->
  <div class="topBar">
    <div class="container">
      <div class="row">
        <div class="col-md-6 hidden-sm hidden-xs">
          <ul class="list-inline">
            <li>
              <a href="#">
                <i class="fa fa-twitter"></i>
              </a>
            </li>
            <li>
              <a href="#">
                <i class="fa fa-facebook"></i>
              </a>
            </li>
            <!-- <li><a href="#"><i class="fa fa-dribbble"></i></a></li> <li><a href="#"><i class="fa fa-vimeo"></i></a></li> <li><a href="#"><i class="fa fa-tumblr"></i></a></li> -->
          </ul>
        </div>
        <div class="col-md-6 col-xs-12">
          <ul class="list-inline pull-right">
            <!-- <li><span><a data-toggle="modal" href='.login-modal'>ログイン</a><small>or</small><a data-toggle="modal" href='#signup'>新規登録</a></span></li> -->
            <li class="dropdown searchBox">
              <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">
                <i class="fa fa-search"></i>
              </a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li>
                  <span class="input-group">
                    <input type="text" class="form-control" placeholder="Search…" aria-describedby="basic-addon2">
                    <span class="input-group-addon" id="basic-addon2">検索</span>
                  </span>
                </li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="cart_page.html" class="dropdown-toggle" data-toggle="dropdown disabled">
                <i class="fa fa-shopping-cart"></i>¥0</a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li>ショッピングカート</li>
                <li>
                  <a href="single_product.html">
                    <div class="media">
                      <%= image_tag("home/cart-items/cart-item-01.jpg", :class => "media-left media-object", :alt => "cart-Image") %>
                      <div class="media-body">
                        <h5 class="media-heading">INCIDIDUNT UT
                          <br>
                          <span>2 X 199円</span></h5>
                      </div>
                    </div>
                  </a>
                </li>
                <li>
                  <a href="single_product.html">
                    <div class="media">
                      <%= image_tag("home/cart-items/cart-item-01.jpg", :class => "media-left media-object", :alt => "cart-Image") %>
                      <div class="media-body">
                        <h5 class="media-heading">INCIDIDUNT UT
                          <br>
                          <span>2 X 199円</span></h5>
                      </div>
                    </div>
                  </a>
                </li>
                <li>
                  <div class="btn-group" role="group" aria-label="...">
                    <button type="button" class="btn btn-default" onclick="location.href='cart_page.html';">カートを見る</button>
                    <button type="button" class="btn btn-default" onclick="location.href='checkout_step_1.html';">購入する</button>
                  </div>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <!-- NAVBAR -->
  <nav class="navbar navbar-main navbar-default" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to potepan_index_path, class: 'navbar-brand' do %>
        <%= image_tag("logo.png") %>
        <% end %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li class="active">
            <%= link_to 'Home', potepan_index_path %>
          </li>
          <li class="dropdown megaDropMenu">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false">Shop</a>
            <ul class="dropdown-menu row">
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>レディース</li>
                  <li>
                    <a href="product_grid_left_sidebar.html">トップス</a>
                  </li>
                  <li>
                    <a href="product_grid_left_sidebar.html">アウター</a>
                  </li>
                  <li>
                    <a href="product_grid_left_sidebar.html">ボトムス</a>
                  </li>
                  <li>
                    <a href="product_grid_left_sidebar.html">靴</a>
                  </li>
                  <!-- <li><a href="product-grid-right-sidebar.html">Products Sidebar Right</a></li> <li><a href="product-grid-3-col-filter.html">Products 3 Columns V1</a></li> <li><a href="product-grid-3-col.html">Products 3 Columns V2</a></li> <li><a
                href="product-grid-4-col.html">Products 4 Columns</a></li> -->
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <!-- <li>Products List View</li> <li><a href="product-list-left-sidebar.html">Products Sidebar Left</a></li> <li><a href="product-list-right-sidebar.html">Products Sidebar Right</a></li> -->
                  <li class="listHeading">メンズ</li>
                  <li>
                    <a href="product_grid_left_sidebar.html">トップス</a>
                  </li>
                  <li>
                    <a href="product_grid_left_sidebar.html">アウター</a>
                  </li>
                  <li>
                    <a href="product_grid_left_sidebar.html">ボトムス</a>
                  </li>
                  <li>
                    <a href="product_grid_left_sidebar.html">靴</a>
                  </li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>キッズ</li>
                  <li>
                    <a href="product_grid_left_sidebar.html">トップス</a>
                  </li>
                  <li>
                    <a href="product_grid_left_sidebar.html">アウター</a>
                  </li>
                  <li>
                    <a href="product_grid_left_sidebar.html">ボトムス</a>
                  </li>
                  <li>
                    <a href="product_grid_left_sidebar.html">靴</a>
                  </li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>アクセサリー</li>
                  <li>
                    <a href="product_grid_left_sidebar.html">モバイルケース・アクセサリー</a>
                  </li>
                  <li>
                    <a href="product_grid_left_sidebar.html">財布・革小物</a>
                  </li>
                  <li>
                    <a href="product_grid_left_sidebar.html">腕時計</a>
                  </li>
                  <li>
                    <a href="product_grid_left_sidebar.html">帽子</a>
                  </li>
                </ul>
                <!-- <a href="#" class="menu-photo"><img src="img/menu-photo.jpg" alt="menu-img"></a> -->
              </li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">About US</a>
            <ul class="dropdown-menu dropdown-menu-left">
              <li>
                <%= link_to 'About Us', potepan_about_us_path %>
              </li>
              <!-- <li><a href="signup.html">Register</a></li> <li><a href="signup-login.html">Register or Login</a></li> <li><a href="login.html">Login</a></li> -->
              <!-- <li><a href="lost-password.html">Password Recovery</a></li> -->
              <li>
                <%= link_to 'Privacy Policy', potepan_privacy_policy_path %>
              </li>
              <!-- <li><a href="terms-and-conditions.html">Terms &amp; Conditions</a></li> -->
              <!-- <li><a href="404.html">404 Not Found</a></li> -->
              <!-- <li><a href="coming-soon.html">Coming Soon</a></li> -->
            </ul>
          </li>
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">blog</a>
            <ul class="dropdown-menu dropdown-menu-right">
              <!-- <li><a href="blog-right-sidebar.html">Right Sidebar</a></li> -->
              <li>
                <%= link_to 'Left Sidebar', potepan_blog_left_sidebar_path %>
              </li>
              <!-- <li><a href="blog-fullwidth.html">Full Width</a></li> <li><a href="blog-single-fullwidth.html">Single Post</a></li> <li><a href="blog-single-right-sidebar.html">Single Right Sidebar</a></li> -->
              <li>
                <%= link_to 'Single Left Sidebar', potepan_blog_single_left_sidebar_path %>
              </li>
            </ul>
          </li>
          <!-- <li class="dropdown"> <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account</a> <ul class="dropdown-menu dropdown-menu-right"> <li><a
        href="account-dashboard.html">Dashboard</a></li> <li><a href="account-profile.html">Profile</a></li> <li><a href="account-all-orders.html">All Orders</a></li> <li><a href="account-single-order.html">Single Order</a></li> <li><a
        href="account-wishlist.html">Wishlist</a></li> <li><a href="account-address.html">Address</a></li> </ul> </li> -->
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
  </nav>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <%= render 'layouts/head' %>
  <%= csrf_meta_tags %>

</head>

<body>
  <div class="main-wrapper">
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= render 'layouts/copyright' %>
  </div>
  <%= render 'layouts/modals' %>
  <%= javascript_include_tag 'application' %>
</body>

</html>

app/views/potepan/categories/show.html.erb
<% provide(:title, @taxon.name) %>

<%= render partial: "potepan/shared/light_section_top", locals: { name: @taxon.name } %>

<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <%= render partial: "potepan/shared/sidebar", locals: { taxonomies: @taxonomies } %>
      <div class="col-md-9 col-sm-8 col-xs-12">
        <div class="row filterArea">
          <div class="col-xs-6">
            <%= form_tag(potepan_category_path(params[:id]), method: :get) do %>
            <%= select_tag 'order', options_for_select([['並び替え', '0'], ['新着順', 'newest'], ['安い順', 'price-asc'], ['高い順', 'price-dsc'], ['古い順', 'oldest']], selected: params[:order] || 'newest'), { class: "select-drop", onChange: "this.form.submit()" } %>
            <% end %>
          </div>
          <div class="col-xs-6">
            <div class="btn-group pull-right" role="group">
              <button type="button" class="btn btn-default active" onclick="window.location.href='product_grid_left_sidebar.html'">
                <i class="fa fa-th" aria-hidden="true"></i>
                <span>Grid</span></button>
              <button type="button" class="btn btn-default" onclick="window.location.href='product_list_left_sidebar.html'">
                <i class="fa fa-th-list" aria-hidden="true"></i>
                <span>List</span></button>
            </div>
          </div>
        </div>
        <div class="row">
          <%= render partial: "potepan/shared/product", collection: @products %>
        </div>
      </div>
    </div>
  </div>
</section>

<%= render partial: "potepan/shared/light_section_bottom" %>

app/views/potepan/home/_new_product.html.erb
<div class="slide">
  <div class="productImage clearfix">
    <%= image_tag(new_product.images.first.attachment.url(:product), :alt => "featured-product-img") %>
    <div class="productMasking">
      <ul class="list-inline btn-group" role="group">
        <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
        <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
        <li><a data-toggle="modal" href=".quick-view" class="btn btn-default"><i class="fa fa-eye"></i></a></li>
      </ul>
    </div>
  </div>
  <div class="productCaption clearfix">
    <%= link_to potepan_product_path(new_product.id) do %>
    <h5>
      <%= new_product.name %>
    </h5>
    <h3>
      <%= new_product.display_price %>
    </h3>
    <% end %>
  </div>
</div>

app/views/potepan/home/_popular_categories.html.erb
<div class="row featuredCollection">
  <div class="col-xs-12">
    <div class="page-header">
      <h4>人気カテゴリー</h4>
    </div>
  </div>
  <div class="col-sm-4 col-xs-12">
    <div class="thumbnail" onclick="location.href='categories/<%= @clothing.ids.first %>';">
      <div class="imageWrapper">
        <%= image_tag("home/featured-collection/featured-collection-01.jpg", :alt => "feature-collection-image") %>
        <div class="masking">
          <%= link_to "View Clothings", potepan_category_path(id: @clothing.ids.first ), class: "btn viewBtn" %>
        </div>
      </div>
      <div class="caption">
        <h4>Clothings</h4>
      </div>
    </div>
  </div>
  <div class="col-sm-4 col-xs-12">
    <div class="thumbnail" onclick="location.href='categories/<%= @bags.ids.first %>';">
      <div class="imageWrapper">
        <%= image_tag("home/featured-collection/featured-collection-02.jpg", :alt => "feature-collection-image") %>
        <div class="masking">
          <%= link_to "View Bags", potepan_category_path(id: @bags.ids.first ), class: "btn viewBtn" %>
        </div>
      </div>
      <div class="caption">
        <h4>Bags</h4>
      </div>
    </div>
  </div>
  <div class="col-sm-4 col-xs-12">
    <div class="thumbnail" onclick="location.href='categories/<%= @mugs.ids.first %>';">
      <div class="imageWrapper">
        <%= image_tag("home/featured-collection/featured-collection-03.jpg", :alt => "feature-collection-image") %>
        <div class="masking">
          <%= link_to "View Mugs", potepan_category_path(id: @mugs.ids.first ), class: "btn viewBtn" %>
        </div>
      </div>
      <div class="caption">
        <h4>Mugs</h4>
      </div>
    </div>
  </div>
</div>

app/views/potepan/products/_related_product.html.erb
<div class="col-md-3 col-sm-6 col-xs-12">
  <div class="productBox">
    <div class="productImage clearfix">
      <%= image_tag(related_product.images.first.attachment.url(:product), :alt => "products-img") %>
      <div class="productMasking">
        <ul class="list-inline btn-group" role="group">
          <li>
            <a data-toggle="modal" href=".login-modal" class="btn btn-default">
              <i class="fa fa-heart"></i>
            </a>
          </li>
          <li>
            <a href="cart_page.html" class="btn btn-default">
              <i class="fa fa-shopping-cart"></i>
            </a>
          </li>
          <li>
            <a class="btn btn-default" data-toggle="modal" href=".quick-view">
              <i class="fa fa-eye"></i>
            </a>
          </li>
        </ul>
      </div>
    </div>
    <div class="productCaption clearfix">
      <%= link_to potepan_product_path(related_product.id) do %>
      <h5>
        <%= related_product.name %>
      </h5>
      <h3>
        <%= related_product.display_price %>
      </h3>
      <% end %>
    </div>
  </div>
</div>

app/views/potepan/shared/_filter_by_category.html.erb
<div class="panel panel-default">
  <div class="panel-heading">商品カテゴリー</div>
  <div class="panel-body">
    <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
      <ul class="nav navbar-nav side-nav">
        <% taxonomies.each do |taxonomy| %>
        <li>
          <a href="javascript:;" data-toggle="collapse" data-target="#taxonomy<%= taxonomy.id %>">
            <%= taxonomy.name %>
            <i class="fa fa-plus"></i>
          </a>
          <ul id="taxonomy<%= taxonomy.id %>" class="collapse collapseItem">
            <% taxonomy.root.children.each do |child| %>
            <li>
              <%= link_to potepan_category_path(child.id) do %>
              <i class="fa fa-caret-right" aria-hidden="true"></i>
              <%= child.name %>
              <span>(
                <%= Spree::Product.in_taxon(child).count %> )</span>
              <% end %>
            </li>
            <% end %>
          </ul>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/potepan/shared/_filter_by_color.html.erb
<div class="panel panel-default filterNormal">
  <div class="panel-heading">色から探す</div>
  <div class="panel-body">
    <ul class="list-unstyled">
      <% list_of_colors.each do | color | %>
      <li>
        <%= link_to potepan_products_url(color: color.name) do %>
        <%= color.name %>
        <span>(
          <%= color.variants.count %> )</span>
        <% end %>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/potepan/shared/_filter_by_size.html.erb
<div class="panel panel-default filterNormal">
  <div class="panel-heading">サイズから探す</div>
  <div class="panel-body">
    <ul class="list-unstyled clearfix">
      <% list_of_sizes.each do | size | %>
      <li>
        <%= link_to potepan_products_url(size: size.name) do %>
        <%= size.name %>
        <span>(
          <%= size.variants.count %> )</span>
        <% end %>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/potepan/shared/_light_section_top.html.erb
<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2>
            <%= name %>
          </h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to 'Home', potepan_index_path %>
          </li>
          <li>
            <a href="#">shop</a>
          </li>
          <li class="active">
            <%= name %>
          </li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/potepan/shared/_product.html.erb
<div class="col-sm-4 col-xs-12">
  <div class="productBox">
    <div class="productImage clearfix">
      <%= image_tag(product.display_image.attachment(:large), :alt => "products-img") %>
      <div class="productMasking">
        <ul class="list-inline btn-group" role="group">
          <li>
            <a data-toggle="modal" href=".login-modal" class="btn btn-default">
              <i class="fa fa-heart"></i>
            </a>
          </li>
          <li>
            <a href="cart_page.html" class="btn btn-default">
              <i class="fa fa-shopping-cart"></i>
            </a>
          </li>
          <li>
            <a class="btn btn-default" data-toggle="modal" href=".quick-view">
              <i class="fa fa-eye"></i>
            </a>
          </li>
        </ul>
      </div>
    </div>
    <div class="productCaption clearfix">
      <%= link_to potepan_product_path(product.id) do %>
      <h5>
        <%= product.name %>
      </h5>
      <h3>
        <%= product.display_price %>
      </h3>
      <% end %>
    </div>
  </div>
</div>